name: cicd

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      SKAFFOLD_DEFAULT_REPO: ghcr.io/con2
    steps:
      - uses: actions/checkout@v1
      - uses: daisaru11/setup-cd-tools@v1.0.0
        with:
          skaffold: '2.9.0'
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - uses: docker/setup-buildx-action@v1
      - id: build
        run: |
          skaffold build --file-output build.json
      - name: Store build.json artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-json
          path: build.json

  deploy_staging:
    runs-on: self-hosted
    needs: build
    environment: Staging
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v3
        with:
          name: build-json
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - uses: daisaru11/setup-cd-tools@v1.0.0
        with:
          skaffold: '2.9.0'
      - uses: docker/setup-buildx-action@v1
      - run: |
          npm ci
          cd kubernetes && ENV=staging npx ts-node manifest.ts && cd ..
          skaffold deploy -n kompassi2-staging -a build.json

  deploy_production:
    runs-on: self-hosted
    needs: build
    environment: Production
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v3
        with:
          name: build-json
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - uses: daisaru11/setup-cd-tools@v1.0.0
        with:
          skaffold: '2.9.0'
      - uses: docker/setup-buildx-action@v1
      - run: |
          npm ci
          cd kubernetes && ENV=production npx ts-node manifest.ts && cd ..
          skaffold deploy -n kompassi2-production -a build.json
